---
title: "STAT547 Project 1"
author: "James Spalding & Ryan Winder"
date: "2024-02-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=F}
#packages
library(tidyverse)
library(readxl)
library(DescTools)
```

```{r}
##### Data cleaning #####
#data
patients = read_excel("patients.xlsx")[,1:5]
parkdata = read.csv("parkinsons.csv")

#patients data:
#clean up non-numeric values
#only a few incorrect values, so manually entering data.
patients[2,5] = ".25"
patients[6,5] = "1.5"
patients[12,5] = "4.5"
patients[15,5] = "5.5"
patients[24:31,4:5] = NA
patients$`Stage (H&Y)` = as.numeric(patients$`Stage (H&Y)`)
patients$`Years since diagnosis` = as.numeric(patients$`Years since diagnosis`)

#remove "healthy" from names
subnames = gsub(" \\(.*", "", patients$'Subject code')
patients$`Subject code` = subnames
colnames(patients)[1] = "name"


#parkdata: 
#makes names column match format of patients data
parknames = gsub("p.*S", "S", parkdata$name)
parknames = gsub("_.", "", parknames)

parkdata$name = parknames


##### Joining Tables #####
fulldata = right_join(patients, parkdata, by = "name")
fulldata = fulldata[!is.na(fulldata$Sex), ] #removing cases without a match in patients df
```

```{r}
#function to create descriptive tables
groupDescriptives = function(func){
  df = data.frame(nrow = 31)
  for (i in 6:22) {
    df = cbind(df, 
                   tapply(fulldata[[i]], fulldata[["name"]], func)
                   )
  }
  df = df[,2:18]
  names(df) = names(fulldata)[6:22]
  return(df)
}

meanDF = groupDescriptives("mean")
sdDF = groupDescriptives("sd")
medDF = groupDescriptives("median")
```


# Introduction

```{r}

```

# Exploring Data

```{r}

```

# Methods

```{r}
patients2 <- patients %>%
  arrange(name)

combined_data <- cbind(patients2,meanDF[,-1])
attach(combined_data)

first_test <- data_frame(
  Healthy = c(sum(Sex == "M" & status == 0), sum(Sex == "F" & status == 0)),
  Unhealthy = c(sum(Sex == "M" & status == 1), sum(Sex == "F" & status == 1)),
  row.names = c("Male", "Female")
)

first_test_matrix <- matrix(c(as.numeric(first_test[1,1]),
                              as.numeric(first_test[2,1]),
                              as.numeric(first_test[1,2]),
                              as.numeric(first_test[2,2])),nrow=2)

first_test
mcnemar.test(first_test_matrix) # p-value of .0291, so we reject H0
                                # We can then claim that the probability of getting
                                # parkinson's is not the same for both Men and Women
```

```{r}
M_year_of_diagnosis = c()
F_year_of_diagnosis = c()
j = 1
k = 1

for(i in 1:31) {
  if(!is.na(`Years since diagnosis`[i])) {
    if(Sex[i] == "M") { M_year_of_diagnosis[j] = Age[i] - `Years since diagnosis`[i]
                     j = j + 1}
    if(Sex[i] == "F") { F_year_of_diagnosis[k] = Age[i] - `Years since diagnosis`[i]
                     k = k + 1}
  }
}

M_year_of_diagnosis
F_year_of_diagnosis

# Returns a p-value of .00695. We can reject H0. 
# We have significant evidence that the variability between men and women
# differ for when they are diagnosed with Parkinsons
SiegelTukeyTest(M_year_of_diagnosis,F_year_of_diagnosis,alternative="two.sided")
```


```{r}
difference_function <- function(x, test_to_run = mean) {
  
  function_list <- list(
    Healthy = c(x[status == 0]),
    Unhealthy = c(x[status == 1])
  )
  
  dat1 <- function_list$Healthy
  dat2 <- function_list$Unhealthy
  
  m=length(function_list$Healthy)
  n=length(function_list$Unhealthy)
  tot=m+n
  Dobs=test_to_run(dat1)-test_to_run(dat2)

  nperm=1000
  Dperm=rep(0,nperm)
  alldat=c(dat1,dat2)

  for(i in 1:nperm){
    index=sample(1:tot,m)
    newdat1=alldat[index]
    newdat2=alldat[-index]
    Dperm[i]=test_to_run(newdat1)-test_to_run(newdat2)
  }

  pvalue=sum(abs(Dperm)>=abs(Dobs))/nperm
  pvalue
}

explanatory_variables <- data.frame(
  variables = c("MDVP.Fhi.Hz.", "MDVP.Flo.Hz.", "MDVP.Jitter...", "MDVP.Jitter.Abs.",
                "MDVP.RAP", "MDVP.PPQ", "Jitter.DDP", "MDVP.Shimmer", "MDVP.Shimmer.dB.",
                "Shimmer.APQ3", "Shimmer.APQ5", "MDVP.APQ", "Shimmer.DDA",
                "NHR", "HNR"))
p_values_mean <- c()
p_values_var <- c()
p_values_median <- c()

for(i in 6:20) {
  p_values_mean[i-5] <- difference_function(combined_data[,i])
  p_values_var[i-5] <- difference_function(combined_data[,i], var)
  p_values_median[i-5] <- difference_function(combined_data[,i], median)
}


permutation_tests <- data.frame(
  Variable = explanatory_variables$variables,
  Pval_mean = p_values_mean,
  Pval_var = p_values_var,
  Pval_median = p_values_median
)

permutation_tests
```









```{r}

## useless code :(
# parkdata
# 
# empty_df <- data.frame(matrix(ncol = ncol(parkdata), nrow = 0))
# colnames(empty_df) <- colnames(parkdata)
# 
# rows <- c(6,6,6,6,6,6,6,6,6,6,6,6,6,6,7,6,6,6,6,7,6,6,6,6,7,6,6,6,6,6,6,6)
# name <- c("S01", "S02", "S04", "S05", "S06", "S07", "S08", "S10", "S13", "S16", 
#           "S17", "S18", "S19", "S20", "S21", "S22", "S24", "S25", "S26",
#           "S27", "S31", "S32", "S33", "S34", "S35", "S37", "S39", "S42",
#           "S43", "S44", "S49", "S50")
# 
# for(i in 1:length(rows)) {
#   
#   averages <- colMeans(parkdata_copy[1:rows[i],2:18])
#   newrow <- c(name[i], averages)
# 
#   empty_df %>%
#     rbind(empty_df,newrow)
# }
# 
# empty_df

```



# Results

```{r}

```

